version: "3.8"

services:
  app:
    build: .
    container_name: hw13-api
    ports:
      - "8000:8000"
    restart: always

  nginx:
    image: nginx:latest
    container_name: proxy_app
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always
