apiVersion: apps/v1
kind: Deployment
metadata:
  name: random-string-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: random-string
  template:
    metadata:
      labels:
        app: random-string
    spec:
      containers:
      - name: random-string-container
        image: rukurok/random-string-app:latest
        ports:
        - containerPort: 8082
