apiVersion: v1
kind: Service
metadata:
  name: random-string-service
spec:
  type: NodePort
  selector:
    app: random-string
  ports:
  - port: 80
    targetPort: 8082
    nodePort: 30082
