
global:
  resolve_timeout: 1m

route:
  receiver: 'telegram'
  group_wait: 10s
  group_interval: 30s
  repeat_interval: 1h

receivers:
  - name: 'telegram'
    telegram_configs:
      - bot_token: '7679618821:AAEo2-zMmmjV5nv80HAzt6iDEv6zW5OCNzA'
        chat_id: '1782765405'
        message: '{{ range .Alerts }}{{ .Annotations.summary }}: {{ .Annotations.description }}{{ println }}{{ end }}'
