Vagrant.configure("2") do |config|
  config.vm.define "jenkins-master" do |master|
    master.vm.box = "ubuntu/jammy64"
    master.vm.hostname = "jenkins-master"
    master.vm.network "private_network", type: "dhcp"
    master.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    master.vm.provision "shell", inline: <<-SHELL
      apt update && apt upgrade -y
      apt install -y openjdk-17-jdk wget gnupg
      wget -q -O - https://pkg.jenkins.io/debian/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc
      echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/" | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null
      apt update
      apt install -y jenkins
      systemctl enable --now jenkins

      apt install -y docker.io
      usermod -aG docker jenkins
      usermod -aG docker vagrant
      systemctl restart jenkins
    SHELL
  end

  config.vm.define "jenkins-worker" do |worker|
    worker.vm.box = "ubuntu/jammy64"
    worker.vm.hostname = "jenkins-worker"
    worker.vm.network "private_network", type: "dhcp"
    worker.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 2
    end
    worker.vm.provision "shell", inline: <<-SHELL
      apt update && apt upgrade -y
      apt install -y openjdk-17-jdk docker.io
      usermod -aG docker vagrant

      mkdir -p /home/vagrant/jenkins
      chown -R vagrant:vagrant /home/vagrant/jenkins
    SHELL
  end
end
