---
- name: Install Docker, Docker Compose, and run Nginx
  hosts: web
  become: true

  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        update_cache: true
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu jammy stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        update_cache: true
        state: latest

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create docker-compose.yml
      copy:
        dest: /home/ubuntu/docker-compose.yml
        content: |
          version: '3'
          services:
            web:
              image: nginx
              ports:
                - "80:80"

    - name: Run Docker Compose
      command: docker-compose up -d
      args:
        chdir: /home/ubuntu
